PALF4/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('future/', views.tambahan, name='tambahan'),
    path('story1/', views.story1, name='story1'),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'alfa3.html')

def profile(request):
    return render(request, 'pagetwo.html')

def tambahan(request):
    return render(request, 'pagetambahan.html')

def story1(request):
    return render(request, 'PALF1.html')

homepage/templates/PALF1.html
{% extends "base.html" %}

{% load static %}

{% block loadcss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/stylePALF1.css' %}">
{% endblock loadcss %}


{% block itemnav %}
<ul class="navbar-nav ml-auto">
  <li class="nav-item">
    <a class="nav-link" style="color:black" href="{% url 'homepage:home' %}">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" style="color:black" href="{% url 'homepage:profile' %}">Profile</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" style="color:black" href="{% url 'homepage:tambahan' %}">Future</a>
  </li>
</ul>
{% endblock itemnav %}


{% block poster %}
<div class="row">
    <div class="container">
        <div class="jumbotron j1">
            <img src="{% static 'img/Group 5.png' %}" class="poster">
            <div class="nameposter">MICHAEL ELIAZER</div>
            <div class="price">999,000,000,000,000,000</div>
        </div>    
    </div>  
</div>
<div class="row">
    <br>
</div>
{% endblock poster %}

{% block arrowdown %}
<div class="row">
    <div class="container">
        <div class="jumbotron j1">
            <div class="teks2">Looking for someone with..</div>
            <br>
            <div><img src="{% static 'img/arrow_down.png' %}" class="arrow"></div>
        
            <div><img src="{% static 'img/arrow_down.png' %}" class="arrow"></div>

            <div><img src="{% static 'img/arrow_down.png' %}" class="arrow"></div>
        </div>
    </div>
</div>


<div class="row">
    <br><br>
</div>
{% endblock arrowdown %}

{% block description %}
<div class="row">
    <div class="container">
        <div class="jumbotron j2">
            <div class="container c1">
                <div class="row">
                    <div class="col-5">
                        <img src="{% static 'img/monoposter.jpg' %}" class="mono">
                    </div>
                    <div class="col-7">
                        <h2 class="display-6 teks1">Profile</h2>
                        <hr class="my-4">
                        <p class="teks3">Name : Michael Eliazer</p>
                        <p class="teks3">NPM : 1806191124</p>
                        <p class="teks3">Education : SI UI 2018</p>
                        <p class="teks3">Hobby : Watching Movies, Listening Music, Playing Video Games</p>
                        <p class="teks3">Description : My nickname is Mike. I'm a cheerful and easy going person. But sometimes, I can be temperamental and moody.</p>    
                    </div>        
                </div>    
            </div>
            
            <br><br><br>  
            
            <div class="row">
                <div class="container midel">
                    <p class="teks1">Educational History</p>
                    <br>
                    <table style="width: 100%;">
                        <tr class="teks3">
                            <th>Place</th>
                            <th>Grade</th> 
                            <th>Year</th>
                        </tr>
                        <tr class="teks4">
                            <td>Sang Timur</td>
                            <td>Primary School</td>
                            <td>2006 - 2008</td>
                        </tr>
                        <tr class="teks4">
                            <td>Saint Caroline</td>
                            <td>Primary School</td>
                            <td>2008 - 2012</td>
                        </tr>
                        <tr class="teks4">
                            <td>Van Lith</td>
                            <td>Junior High School</td>
                            <td>2012 - 2015</td>
                        </tr>
                        <tr class="teks4">
                            <td>PENABUR 3 JAKARTA</td>
                            <td>High School</td>
                            <td>2015 - 2018</td>
                        </tr>
                        <tr class="teks4">
                            <td>Universitas Indonesia</td>
                            <td>College</td>
                            <td>2018 - Now</td>
                        </tr>
                        </table>
                </div>
            </div>
        </div>        
    </div>
</div>

<div class="row">
    <br><br><br><br>
</div>
{% endblock description %}


{% block footer %}
<div class="footer">
<div class="row">
    <div class="col-7 teks5"> Copyright @ 2020 Mike</div>
    <div class="col-5 kanan">
        <a href="https://mail.google.com/mail/u/0/?view=cm&fs=1&to=michael.eliazer@gmail.com&su=SUBJECT&body=BODY&tf=1" target="blank"><img src="{% static 'img/gmail1.png' %}" class="icon1"></a>
        <a href="http://line.me/ti/p/~mekel." target="blank"><img src="{% static 'img/line1.png' %}" class="icon3"></a>
        <a href="https://api.whatsapp.com/send?phone=62895322454427&text=what's%20up?" target="blank"><img src="{% static 'img/whatsapp1.png' %}" class="icon2"></a>
        <a href="https://www.instagram.com/michaeleliazer/?hl=en" target="blank"><img src="{% static 'img/instagram1.png' %}" class="icon3"></a>
    </div>
</div>
</div>
{% endblock footer %}

homepage/templates/alfa3.html
{% extends "base.html" %}

{% load static %}

{% block loadcss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/alfa3.css' %}">
{% endblock loadcss %}
    
{% block itemnav %}
<ul class="navbar-nav ml-auto">
  <li class="nav-item">
    <a class="nav-link" style="color:black" href="{% url 'homepage:profile' %}">Profile</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" style="color:black" href="{% url 'homepage:tambahan' %}">Future</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" style="color:black" href="{% url 'homepage:story1' %}">Story 1</a>
  </li>
  <li class="nav-item">
    <a class="nav-link"style="color:black" href="#a">About Me</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" style="color:black" href="#b">Skills</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" style="color:black" href="#c">Experience</a>
  </li>
</ul>
{% endblock itemnav %}

{% block jumbotronwelcome %}
<div class="jumbotron jumbotron-fluid j1">
    <div class="container">
      <h1 class="welkam">WELCOME</h1>
    </div>
  </div>
  
  <br><br>
{% endblock jumbotronwelcome %}

{% block about %}
 <div class="row">
    <div class="container-fluid j3">
      <h2 class="text-center teks1">About Me</h2>
      <p class="text-center teks2">Hello, my name is Michael Eliazer and you can call 
        me Mike. I’m a second year University student who majors 
        in Information System at Universitas Indonesia. I enjoy 
        doing sports and often participate in sport events at Uni. 
        My hobby is watching movies and listening to music.
      </p>
    </div>
  </div>
  <br><br><br>
{% endblock about %}

{% block skills %}
  <h2 class="text-center teks1" id="b">My Skills</h2>

  <br>

  <div class="row">
    <div class="col-sm-4">
      <div class="card">
        <img src="{% static 'img/eaticon.png' %}" class="card-img-top gambarskill" >
        <div class="card-body cb1">
          <h4 class="card-title text-center judulskill">Eat</h4>
          <br>
          <p class="card-text text-center kontenskill">
            Lorem ipsum dolor sit amet et delectus accommodare his consul copiosae 
            legendos at vix ad putent delectus delicata usu. Vidit dissentiet eos cu 
            eum an brute copiosae hendrerit.
          </p>
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="card">
        <img src="{% static 'img/codingicon.png' %}" class="card-img-top gambarskill">
        <div class="card-body cb1">
          <h4 class="card-title text-center judulskill">Coding</h4>
          <br>
          <p class="card-text text-center kontenskill">
            Lorem ipsum dolor sit amet et delectus accommodare his consul copiosae 
            legendos at vix ad putent delectus delicata usu. Vidit dissentiet eos cu 
            eum an brute copiosae hendrerit.
          </p>
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="card" >
        <img src="{% static 'img/designicon.png' %}" class="card-img-top gambarskill" alt="">
        <div class="card-body cb1">
          <h4 class="card-title text-center judulskill">Design</h4>
          <br>
          <p class="card-text text-center kontenskill">
            Lorem ipsum dolor sit amet et delectus accommodare his consul copiosae 
            legendos at vix ad putent delectus delicata usu. Vidit dissentiet eos cu 
            eum an brute copiosae hendrerit.
          </p>
        </div>
      </div>
    </div>
  </div>

  <br><br><br>
  {% endblock skills %}

  {% block experience %}
  <h2 class="text-center teks1" id="c">Experience</h2>

  <br>

  <div class="row">
    <div class="container j4">

      <div class="row">
        <div class="col-md-6">
          <div class="card">
            <div class="card-header text-center judulskill">
              Computers Get Together 2019
            </div>
            <div class="card-body text-center">
              <img src="{% static 'img/cegete.JPG' %}" class="cgt">
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="card">
            <div class="card-header text-center judulskill">
              Compfest 11
            </div>
            <div class="card-body text-center">
              <img src="{% static 'img/timbul.jpg' %}" class="cgt">
            </div>
          </div>
        </div>
      </div>

      <br>

      <div class="row">
        <div class="col-md-6">
          <div class="card">
            <div class="card-header text-center judulskill">
              PMB 2019
            </div>
            <div class="card-body text-center">
              <img src="{% static 'img/mentorpmb.jpg' %}" class="cgt">
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="card">
            <div class="card-header text-center judulskill">
              Olimpiade UI 2018
            </div>
            <div class="card-body text-center">
              <img src="{% static 'img/olim.jpg' %}" class="cgt">
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>

  <br><br><br><br>
  {% endblock experience %}

  {% block contact %}
  <div class="row">
    <div class="container text-center">
      <p class="kontak">Contact me at:</p>
      <br>
      <a href="https://mail.google.com/mail/u/0/?view=cm&fs=1&to=michael.eliazer@gmail.com&su=SUBJECT&body=BODY&tf=1" target="blank"><img src="{% static 'img/gmail.png' %}" class="icon1"></a>
      <a href="http://line.me/ti/p/~mekel." target="blank"><img src="{% static 'img/line.png' %}" class="icon3"></a>
      <a href="https://api.whatsapp.com/send?phone=62895322454427&text=what's%20up?" target="blank"><img src="{% static 'img/whatsapp.png' %}" class="icon2"></a>
      <a href="https://www.instagram.com/michaeleliazer/?hl=en" target="blank"><img src="{% static 'img/instagram.png' %}" class="icon3"></a>
    </div>
  </div>

  <br><br><br><br>
  {% endblock contact %}

homepage/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Third Story</title>

    {% include "snippets/style.html" %}
     
    {% block loadcss %}

    {% endblock loadcss %}
    
    

</head>

<body>

<nav class="navbar navbar-expand-sm navbg">
  <ul class="navbar-nav mr-auto">
    <a class="navbar-brand disabled mek">
      <img src="{% static 'img/lambangweb.png' %}" alt="logo" style="width:55px; margin-right: 5px;">
        MEK. 
    </a>
  </ul>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"><img src="{% static 'img/buttondown.png' %}" class="down"></img></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    {% block itemnav %}

    {% endblock itemnav %}
  </div>
</nav>


{% block jumbotronwelcome %}

{% endblock jumbotronwelcome %}


<div class="container-fluid text-center" id="a">

    {% block about %}

    {% endblock about %}

    {% block skills %}

    {% endblock skills %}

    {% block experience %}

    {% endblock experience %}

    {% block profil %}

    {% endblock profil %}
    
    {% block bio %}

    {% endblock bio %}
    
    {% block galeri %}

    {% endblock galeri %}

    {% block poster %}

    {% endblock poster %}

    {% block arrowdown %}

    {% endblock arrowdown %}

    {% block description %}

    {% endblock description %}
    
    {% block contact %}

    {% endblock contact %}

    {% block footer %}

    {% endblock footer %}
  
</div>

{% include "snippets/scripts.html" %}

</body>
</html>

homepage/templates/pagetambahan.html
{% extends "base.html" %}

{% load static %}

{% block loadcss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/tambahan.css' %}">
{% endblock loadcss %}

{% block itemnav %}
<ul class="navbar-nav ml-auto">
  <li class="nav-item">
    <a class="nav-link" style="color:black" href="{% url 'homepage:home' %}">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" style="color:black" href="{% url 'homepage:profile' %}">Profile</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" style="color:black" href="{% url 'homepage:story1' %}">Story 1</a>
  </li>
</ul>
{% endblock itemnav %}

homepage/templates/pagetwo.html
{% extends "base.html" %}

{% load static %}

{% block loadcss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/pagetwo.css' %}">
{% endblock loadcss %}

{% block itemnav %}
<ul class="navbar-nav ml-auto">
  <li class="nav-item">
    <a class="nav-link" style="color:black" href="{% url 'homepage:home' %}">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" style="color:black" href="#d">Gallery</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" style="color:black" href="{% url 'homepage:tambahan' %}">Future</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" style="color:black" href="{% url 'homepage:story1' %}">Story 1</a>
  </li>
</ul>
{% endblock itemnav %}

{% block profil %}
<div class="row">
  <br><br><br><br>
</div>

<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <img src="{% static 'img/mekel2.png' %}">  
  </div>
  <div class="col-md-4"></div>
</div>

<div class="row">
  <br>
</div>

<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <p class="teks1">ini profil ku:)</p>
  </div>
  <div class="col-md-4"></div>
</div>

<div class="row">
  <br><br><br><br><br>
</div>
{% endblock profil %}


{% block bio %}
<div class="row">
  <div class="col-lg"></div>
  <div class="col-lg-4">
    <div class="card c1" >
      <div class="card-body">
          <p class="teks2">Cerita singkat</p>
      </div>
      <div class="card-body">
        <p class="teks3">Halo nama saya Michael Eliazer, 
          saya sedang mempelajari cara membuat suatu website, 
          Jadi website ini masih dalam tahap perkembangan. 
          Mohon bersabar untuk versi lebih lanjutnya hehe :v</p>
    </div>
    </div>
  </div>
  <div class="col-lg"></div>
  <div class="col-lg-4">
    <div class="card c1">
      <div class="card-body">
          <p class="teks2">Biodata</p>
      </div>
      <div class="card-body cb1">
        <p class="teks4"><b>Nama</b> : Michael Eliazer Intan<br>
          <b>Alamat</b> : Jalan Haji Amat No 3<br>
          <b>Tanggal Lahir</b> : 11 Sept 2000<br>
          <b>Hobi</b> : Olahraga & mendengarkan musik<br>
          <b>NPM</b> : 1806191124<br>
          <b>Pendidikan</b> : <br>
          * SDK Sang Timur<br>
          * SD Saint Caroline<br>
          * SMAK 3 PENABUR<br>
          * Universitas Indonesia
          </p>
    </div>
    </div>
  </div>
  <div class="col-lg"></div>
</div>

<div class="row">
  <br><br><br><br><br><br><br>
</div>
{% endblock bio %}

{% block galeri %}
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <p class="teks5" id="d">Galeri Foto</p>
  </div>
  <div class="col-md-4"></div>
</div>

<div class="row">
  <br><br><br><br><br>
</div>

<div class="row">
  <div class="col-lg"></div>
  <div class="col-lg-5">
    <img src="{% static 'img/Group1.png' %}">
    <br><br><br>
  </div>
  <div class="col-lg-5">
    <img src="{% static 'img/group2.png' %}">
    <br><br><br><br>
  </div>
  <div class="col-lg"></div>
</div>

<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-5">
    <img src="{% static 'img/pict5.png' %}">
  </div>
  <div class="col-md-3"></div>
</div>

<div class="row">
  <br><br><br>
</div>

<div class="row">
  <div class="col-lg"></div>
  <div class="col-lg-5">
    <img src="{% static 'img/pict6.png' %}">
    <br><br><br>
  </div>
  <div class="col-lg-5">
    <img src="{% static 'img/pict7.png' %}">
    <br><br><br>
  </div>
  <div class="col-lg"></div>
</div>

<div class="row">
  <br><br><br><br><br><br><br>
</div>
{% endblock galeri %}

homepage/templates/snippets/scripts.html
{% load static %}

<script src="{% static 'jquery/jquery.js' %}" type="text/javacript"></script>
<script src="{% static 'popper/popper.js' %}" type="text/javacript"></script>
<script src="{% static 'bootstrap/bootstrap.js' %}" type="text/javacript"></script>

homepage/templates/snippets/style.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/bootstrap.css' %}">